# Generated by Django 4.1 on 2022-09-02 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('grammar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeaImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('tea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chayok.tea')),
            ],
        ),
    ]
