# Generated by Django 4.1 on 2022-09-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chayok', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tea',
            name='grammar',
            field=models.IntegerField(blank=True),
        ),
    ]
