# Generated by Django 4.1 on 2022-09-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chayok', '0002_alter_tea_description_alter_tea_grammar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tea',
            name='grammar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
